---

name: kibosh

releases:
  - name: kibosh
    version: latest
  - name: example-chart
    version: latest
  - name: docker
    version: latest
  - name: cf-cli
    version: latest

stemcells:
  - alias: ((stemcell))
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: loader
  instances: 1
  azs: [z1]
  lifecycle: errand
  jobs:
    - name: load-image
      release: kibosh
    - name: example-chart
      release: example-chart
    - name: docker
      release: docker
  properties:
    chart_path: /var/vcap/packages/example-chart/example-chart
    registry:
      server: ((registry-server))
      username: ((registry-user))
      password: ((registry-pass))
  vm_type: default
  stemcell: ((stemcell))
  networks:
    - name: default

- name: registrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  jobs:
    - name: register-broker
      release: kibosh
    - name: cf-cli-6-linux
      release: cf-cli
  properties:
    broker_name: spacebears-broker
    disable_ssl_cert_verification: true
    enable_service_access: true
    cf:
      api_url: https://api.v3.pcfdev.io
      admin_username: admin
      admin_password: admin
  vm_type: default
  stemcell: ((stemcell))
  networks:
    - name: default

- name: kibosh_node
  instances: 1
  azs: [z1]
  jobs:
    - name: kibosh
      release: kibosh
    - name: example-chart
      release: example-chart
  properties:
    kibosh:
      username: admin
      password: ((kibosh-password))
      helm_chart_dir: /var/vcap/packages/example-chart/example-chart
      ca_data: ((k8s-cluster-ca-cert))
      server: ((k8s-cluster-server))
      token: ((k8s-cluster-token))
    registry:
      server: ((registry-server))
      username: ((registry-user))
      password: ((registry-pass))

  vm_type: default
  cloud_properties:
    tags:
      - allow-ssh
  stemcell: ((stemcell))
  persistent_disk_type: default
  networks:
    - name: default

- name: deregistrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  jobs:
    - name: delete-all-and-deregister
      release: kibosh
  properties:
    broker_name: spacebears-broker
    disable_ssl_cert_verification: true
    cf:
      api_url: https://api.v3.pcfdev.io
      uaa_url: https://uaa.v3.pcfdev.io
      admin_username: admin
      admin_password: admin
  vm_type: default
  stemcell: ((stemcell))
  networks:
    - name: default

variables:
- name: kibosh-password
  type: password
